### ISSUE TITLE
Where is the button "Gamepad L1 R1 L2 R2 ..." come from?

### ISSUE THREAD

**Issue by luciddream-tsin** [DarknessFX/UEPlaystationGamepad#1]
Hello, I am try to use your code in my project, but I don't know where the following buttong come from:
![图片](https://github.com/DarknessFX/UEPlaystationGamepad/assets/92364028/fe6f80a2-86c4-45bc-89a3-58e5e3ff081c)

In my project, I couldn't find those items , and I've searched through your code extensively. Unfortunately, I'm unable to determine what happened...

**Comment by DarknessFX** [comment]
Hi, 
Inside Unreal Engine, go to menu Edit > Editor Preferences, section General - Experimental > User Interface change to PS4.
After this change Unreal Editor will show gamepad buttons using Dualshock names (L1, R1, Square, etcs).

**Comment by luciddream-tsin** [comment]
Thanks!!
